---
- hosts: "{{ target }}"
  remote_user: "{{ user }}"
  become: true
  tasks:

  - name: Install PreReq Fedora
    dnf:
      name: "{{ item }}"
      state: latest
    when: os == "Fedora"
    with_items:
      - npm
      - ruby
      - ruby-devel
      - git

  - name: Install PreReq Ubuntu
    apt:
      name: "{{ item }}"
      state: latest
    when: os == "Ubuntu"
    with_items:
      - npm
      - git
      - python-software-properties
      - ruby
      - ruby-dev

  - name: Install "surge" package globally.
    npm:
      name: surge
      global: yes

# Ansible bug: on Ubuntu gem sometimes not work
  - name: Install "travis" package.
    gem:
      name: travis
      state: lastest
      include_dependencies: true
